# Generated by Django 5.2.8 on 2025-11-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('option_one', models.CharField(max_length=5000)),
                ('option_two', models.CharField(max_length=5000)),
                ('option_three', models.CharField(max_length=5000)),
                ('option_four', models.CharField(max_length=5000)),
                ('option_five', models.CharField(max_length=5000)),
                ('option_six', models.CharField(max_length=5000)),
                ('option_seven', models.CharField(max_length=5000)),
                ('option_eight', models.CharField(max_length=5000)),
                ('option_nine', models.CharField(max_length=5000)),
                ('option_ten', models.CharField(max_length=5000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
