# Generated by Django 5.2.8 on 2025-11-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattempt_quiz_useranswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.CharField(max_length=5000),
        ),
    ]
