# Generated by Django 5.2.8 on 2025-11-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_useranswer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
    ]
