# Generated by Django 5.2.8 on 2025-11-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quizattempt_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
