# Generated by Django 5.2.8 on 2025-11-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_option_eight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User Answer Question'},
        ),
    ]
